public class ConstantsForPolandReport {
	public static final String SALES_FA_REPORT = 'JPK_FA_SaleInv';
    public static final String VAT_REPORT = 'JPK_VAT';
    public static final String KR_ALL_ENTRIES = 'JPK_KR_AllEntries';
    public static final String SALES_FA_REPORT_NAME = 'JPK_FA_SaleInv Report';
    public static final String VAT_REPORT_NAME = 'JPK_VAT Report';
    public static final String ALL_ENTRIES_REPORT_NAME = 'PolUnifiedExportksiegi_JPK_KR_AllEntries';
    public static final String CUSTOM_EXCEPTION_MESSAGE = 'Please select a report type!';
    
	public static final String FA_CONTAINER_TAG = 'JPK0';	
	public static final String FA_HEADER = 'Naglowek0';
	public static final String FA_HEADER = 'KodFormularza0';
	public static final String FA_HEADER = 'Naglowek2';
	public static final String FA_HEADER = 'Naglowek3';
	public static final String FA_HEADER = 'Naglowek4';
	public static final String FA_HEADER = 'Naglowek5';
	public static final String FA_HEADER = 'Naglowek6';
	public static final String FA_HEADER = 'Naglowek7';
	public static final String FA_HEADER = 'Naglowek8';
	public static final String FA_HEADER = 'Podmiot0';
	public static final String FA_HEADER = 'IdentyfikatorPodmiotu0';
	public static final String FA_HEADER = 'AdresPodmiotu0';
	public static final String FA_HEADER = 'Faktura0';
	public static final String FA_HEADER = 'Faktura7';
	public static final String FA_HEADER = 'Faktura8';
	public static final String FA_HEADER = 'Faktura4';
	public static final String FA_HEADER = 'Faktura14';
	public static final String FA_HEADER = 'Faktura23';	
	public static final String FA_HEADER = 'FakturaCtrl0';
	public static final String FA_HEADER = 'FakturaCtrl1';
	public static final String FA_HEADER = 'FakturaCtrl2';
	public static final String FA_HEADER = 'FakturaWiersz0';
	public static final String FA_HEADER = 'StawkiPodatku0';
	public static final String FA_HEADER = 'FakturaWierszCtrl0';
	public static final String FA_HEADER = 'FakturaWierszCtrl1';
	public static final String FA_HEADER = 'FakturaWierszCtrl2';
	public static final String FA_HEADER = 'VAT_SprzedazWiersz0';
	public static final String FA_HEADER = 'JPK1';
	public static final String FA_HEADER = 'KodFormularza1';
	public static final String FA_HEADER = 'KodFormularza0';
	public static final String FA_HEADER = 'Faktura1';
	public static final String FA_HEADER = 'FakturaWiersz1';
	
	public static final String FA_HEADER = 'VAT_JPK1';
	public static final String FA_HEADER = 'VAT_JPK0';
	public static final String FA_HEADER = 'VAT_KodFormularza1';
	public static final String FA_HEADER = 'VAT_KodFormularza0';
	
	
	public static final String FA_HEADER = 'KR_Dziennik0';
	public static final String FA_HEADER = 'KR_KontoZapis0';
	public static final String FA_HEADER = 'KR_Dziennik1';
	public static final String FA_HEADER = 'KR_KontoZapis1';
	public static final String FA_HEADER = 'KR_ZOiS1';
	public static final String FA_HEADER = 'KR_ZOiS1';
	public static final String FA_HEADER = 'KR_JPK1';
	public static final String FA_HEADER = 'KR_JPK0';
	public static final String FA_HEADER = 'KR_ZOiS0';
	public static final String FA_HEADER = 'KR_JPK1';
	public static final String FA_HEADER = 'KR_JPK0';
	public static final String FA_HEADER = 'KR_ZOiS0';
	public static final String FA_HEADER = 'KR_ZOiS1';
	
	
	public static final String FA_HEADER = 'FakturaCreditNote0';
	public static final String FA_HEADER = 'FakturaCreditNoteLines0';
	public static final String FA_HEADER = 'VAT_ZakupWiersz0';

	public static final String FA_HEADER = 'FakturaCreditNote0';
	
	public static final String FA_HEADER = 'FakturaCreditNote0';
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}